"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 08:53:30.374867
"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")  # a plain PostgreSQL server needs it enabled once
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_geospatial_table('countries',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_countries_geom', 'countries', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('data_sources',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='VERSION2_XLSX, CATCHMENT_XLSX, MINEDUC_API ...'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('provinces',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('school_levels',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False, comment='NUR, PRI, LSE, USE, TVE, TTC'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('entry_age', sa.SmallInteger(), nullable=True),
    sa.Column('duration_years', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('full_day', sa.Boolean(), nullable=False, comment='no double shift: every class group needs a room'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_table('districts',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False, comment='NISR code when known; the upper-case name for now'),
    sa.Column('province_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_districts_geom', 'districts', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('grades',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('level_id', sa.SmallInteger(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False, comment='1 = entry grade of the level'),
    sa.Column('next_grade_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['school_levels.id'], ),
    sa.ForeignKeyConstraint(['next_grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True, comment='API endpoint or file name'),
    sa.Column('academic_year_id', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False, comment='running, success, partial, failed'),
    sa.Column('rows_received', sa.Integer(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.SmallInteger(), nullable=False),
    sa.Column('academic_year_id', sa.SmallInteger(), nullable=False),
    sa.Column('classroom_capacity', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['school_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'academic_year_id')
    )
    op.create_table('projection_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_year_id', sa.SmallInteger(), nullable=False),
    sa.Column('end_year', sa.SmallInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scenario_intake',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False, comment='entry grade, e.g. N1'),
    sa.Column('district_id', sa.SmallInteger(), nullable=False),
    sa.Column('new_entrants', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False, comment='catchment, manual, csv_upload'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['projection_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'year', 'grade_id', 'district_id')
    )
    op.create_index(op.f('ix_scenario_intake_scenario_id'), 'scenario_intake', ['scenario_id'], unique=False)
    op.create_geospatial_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False, comment='NISR code when known; DISTRICT/SECTOR for now'),
    sa.Column('district_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_geospatial_index('idx_sectors_geom', 'sectors', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mineduc_code', sa.String(length=20), nullable=False, comment='school_code'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mineduc_code')
    )
    op.create_geospatial_index('idx_schools_geom', 'schools', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('catchment_population',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'year', 'age')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('mineduc_classroom_id', sa.String(length=64), nullable=False, comment='test_code: cleaned room ID'),
    sa.Column('source_classroom_id', sa.String(length=64), nullable=True, comment='classroom_id as recorded in the roster'),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'mineduc_classroom_id')
    )
    op.create_index(op.f('ix_classrooms_school_id'), 'classrooms', ['school_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.Column('academic_year_id', sa.SmallInteger(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=False, comment='table the issue is about'),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('issue_code', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_school_id'), 'data_quality_issues', ['school_id'], unique=False)
    op.create_table('class_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('academic_year_id', sa.SmallInteger(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('combination', sa.String(length=100), nullable=True, comment='subject combination / trade'),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('students_total', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_groups_classroom_id'), 'class_groups', ['classroom_id'], unique=False)
    op.create_index('ix_class_groups_year_school', 'class_groups', ['academic_year_id', 'school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_class_groups_year_school', table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_classroom_id'), table_name='class_groups')
    op.drop_table('class_groups')
    op.drop_index(op.f('ix_data_quality_issues_school_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_classrooms_school_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_table('catchment_population')
    op.drop_geospatial_index('idx_schools_geom', table_name='schools', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('schools')
    op.drop_geospatial_index('idx_sectors_geom', table_name='sectors', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('sectors')
    op.drop_index(op.f('ix_scenario_intake_scenario_id'), table_name='scenario_intake')
    op.drop_table('scenario_intake')
    op.drop_table('projection_scenarios')
    op.drop_table('level_norms')
    op.drop_table('import_runs')
    op.drop_table('grades')
    op.drop_geospatial_index('idx_districts_geom', table_name='districts', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('districts')
    op.drop_table('school_levels')
    op.drop_table('provinces')
    op.drop_table('data_sources')
    op.drop_geospatial_index('idx_countries_geom', table_name='countries', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('countries')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
