"""
Build dashboard/src/site/rwandaMap.ts: Rwanda's district outlines as small SVG paths for the landing page's
illustrations (public page: drawn from the bundle, no API call).

The shapes come from data-sources/boundaries/districts.geojson (scripts/build_boundaries.py), projected to a
600-px-wide plane and simplified (Douglas-Peucker). The dots are illustrative positions inside the country, not
school locations.

Run:  python scripts/build_landing_map.py
"""
from __future__ import annotations

import json
import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data-sources" / "boundaries" / "districts.geojson"
OUT = ROOT / "dashboard" / "src" / "site" / "rwandaMap.ts"
WIDTH = 600
TOLERANCE = 0.7  # px
DOTS = 150


def polygons(geom: dict) -> list[list[list[list[float]]]]:
    return [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]


def simplify(pts: list[tuple[float, float]], tol: float) -> list[tuple[float, float]]:
    """Douglas-Peucker."""
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-12
    far, idx = -1.0, 0
    for i in range(1, len(pts) - 1):
        x, y = pts[i]
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / norm if (dx or dy) else math.hypot(x - x1, y - y1)
        if d > far:
            far, idx = d, i
    if far <= tol:
        return [pts[0], pts[-1]]
    return simplify(pts[: idx + 1], tol)[:-1] + simplify(pts[idx:], tol)


def area(ring: list[tuple[float, float]]) -> float:
    return abs(sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]))) / 2


def inside(x: float, y: float, ring: list[tuple[float, float]]) -> bool:
    hit = False
    for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]):
        if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
            hit = not hit
    return hit


def main() -> None:
    features = json.loads(SRC.read_text(encoding="utf-8"))["features"]
    lons = [p[0] for f in features for poly in polygons(f["geometry"]) for ring in poly for p in ring]
    lats = [p[1] for f in features for poly in polygons(f["geometry"]) for ring in poly for p in ring]
    lat0 = (min(lats) + max(lats)) / 2
    kx = math.cos(math.radians(lat0))
    scale = WIDTH / ((max(lons) - min(lons)) * kx)
    height = round((max(lats) - min(lats)) * scale)

    def project(lon: float, lat: float) -> tuple[float, float]:
        return (lon - min(lons)) * kx * scale, (max(lats) - lat) * scale

    districts, outer_rings = [], []
    for f in sorted(features, key=lambda f: f["properties"]["d"]):
        parts, best = [], []
        for poly in polygons(f["geometry"]):
            for k, ring in enumerate(poly):
                pts = simplify([project(*p[:2]) for p in ring], TOLERANCE)
                if len(pts) < 4 or area(pts) < 4:
                    continue
                parts.append("M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts[:-1]) + "Z")
                if k == 0:
                    outer_rings.append(pts)
                    best = max(best, pts, key=area) if best else pts
        cx = sum(x for x, _ in best) / len(best)
        cy = sum(y for _, y in best) / len(best)
        districts.append({"name": f["properties"]["d"], "d": "".join(parts), "cx": round(cx, 1), "cy": round(cy, 1)})

    rng = random.Random(2026)
    dots = []
    while len(dots) < DOTS:
        x, y = rng.uniform(0, WIDTH), rng.uniform(0, height)
        if any(inside(x, y, r) for r in outer_rings):
            dots.append([round(x, 1), round(y, 1)])

    ts = (
        "/**\n * Rwanda's districts as SVG paths for the landing page's illustrations.\n"
        " * Generated by scripts/build_landing_map.py from data-sources/boundaries/districts.geojson — do not edit.\n"
        " * `dots` are illustrative positions inside the country, not school locations.\n */\n"
        f"export const MAP_WIDTH = {WIDTH};\nexport const MAP_HEIGHT = {height};\n\n"
        "export interface DistrictShape {\n  name: string;\n  d: string; // SVG path\n  cx: number; // label / marker point\n  cy: number;\n}\n\n"
        f"export const DISTRICTS: DistrictShape[] = {json.dumps(districts, separators=(',', ':'))};\n\n"
        f"export const DOTS: [number, number][] = {json.dumps(dots, separators=(',', ':'))};\n"
    )
    OUT.write_text(ts, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(districts)} districts, {WIDTH}x{height}, {len(ts) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
